[package]
name = "dos_to_go"
authors = ["onyx :3 <nyxmailbox@proton.me>"]
version = "0.0.5"
edition = "2021"
license = "MIT"
description = "Run Rust on DOS!"
repository = "https://github.com/0x0nyx98/dos_to_go"
readme = "readme.md"

[dependencies]
dos_to_go-procmacro = { version = "1.0.0" }
